# Generated by Django 6.0.4 on 2026-05-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('graduacao', models.CharField(choices=[('branca', 'Faixa Branca'), ('azul', 'Faixa Azul'), ('roxa', 'Faixa Roxa'), ('marrom', 'Faixa Marrom'), ('preta', 'Faixa Preta')], max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/')),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
