# Generated by Django 6.0.4 on 2026-05-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
    ]
