# Generated by Django 6.0.4 on 2026-05-04 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_academia_aluno_academia_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('dono', 'Dono'), ('professor', 'Professor')], default='professor', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='academia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alunos.academia'),
        ),
    ]
